# Generated by Django 4.1.6 on 2023-07-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_photo',
            field=models.ImageField(blank=True, default='profile/default.png', null=True, upload_to='images/'),
        ),
    ]
