# Generated by Django 4.1.6 on 2023-04-12 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=30, null=True)),
                ('brand_name', models.CharField(choices=[('YONEX', 'YONEX'), ('MIZUNO', 'MIZUNO'), ('DUNLOP', 'DUNLOP')], default='YONEX', max_length=20)),
                ('series_name', models.CharField(choices=[('VOLTRAGE', 'VOLTRAGE'), ('GEOBREAK', 'GEOBREAK'), ('F-LASER', 'F-LASER'), ('YONEX_OTHERS', 'YONEX_OTHERS'), ('SCUD', 'SCUD'), ('DIOS', 'DIOS'), ('MIZUNO_OTHERS', 'MIZUNO_OTHERS'), ('GALAXEED', 'GALAXEED'), ('JETSTORM', 'JETSTORM'), ('DUNLOP_OTHERS', 'DUNLOP_OTHERS')], default='VOLTRAGE', max_length=20)),
                ('item_photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('item_position', models.CharField(choices=[('後衛', '後衛'), ('前衛', '前衛'), ('前・後衛', '前・後衛')], default='後衛', max_length=5)),
                ('release_date', models.DateField()),
                ('display', models.BooleanField(default=False)),
            ],
        ),
    ]
