# Generated by Django 4.1.6 on 2023-04-12 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.item'),
            preserve_default=False,
        ),
    ]
