# Generated by Django 4.1.6 on 2023-06-11 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_post_likes_count_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes_count',
        ),
    ]
