# Generated by Django 4.1.6 on 2023-06-20 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_brand_remove_item_brand_name_remove_item_series_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.brand'),
        ),
    ]
