# Generated by Django 4.1.6 on 2023-07-21 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
        ('app', '0010_alter_brand_name_alter_item_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='item',
            name='position',
        ),
        migrations.RemoveField(
            model_name='item',
            name='series',
        ),
        migrations.AlterUniqueTogether(
            name='series',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='series',
            name='brand',
        ),
        migrations.AlterField(
            model_name='post',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item'),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.DeleteModel(
            name='Series',
        ),
    ]
