# Generated by Django 4.1.6 on 2023-07-25 05:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0008_rename_liked_posts_customuser_liked_reviews'),
        ('item', '0002_alter_item_item_photo'),
        ('app', '0011_remove_item_brand_remove_item_position_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Review',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='review',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'review')},
        ),
    ]
