# Generated by Django 4.1.6 on 2023-08-30 04:22

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0012_rename_post_review_rename_post_like_review_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='Favorite',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='likes_count',
            new_name='favorites_count',
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
