# Generated by Django 4.1.6 on 2023-07-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_brand_name_alter_item_brand_and_more'),
        ('accounts', '0005_customuser_liked_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='liked_posts',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_by', to='app.post'),
        ),
    ]
