# Generated by Django 4.1.6 on 2023-07-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_item_brand_remove_item_position_and_more'),
        ('accounts', '0006_alter_customuser_liked_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='liked_posts',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='app.post'),
        ),
    ]
