# Generated by Django 4.1.6 on 2023-07-25 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_liked_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='liked_posts',
            new_name='liked_reviews',
        ),
    ]
