# Generated by Django 4.1.6 on 2023-08-30 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_like_favorite_and_more'),
        ('accounts', '0008_rename_liked_posts_customuser_liked_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='liked_reviews',
        ),
        migrations.AddField(
            model_name='customuser',
            name='favorite_reviews',
            field=models.ManyToManyField(blank=True, related_name='favorite_by', to='app.review'),
        ),
    ]
